### ISSUE TITLE
config.server.js not copied from config.server.js.default by make

### ISSUE THREAD

**Issue by dev-id** [arxanas/drafts.ninja#17]
When running make, config.server.js is not generated.

**Comment by arxanas** [comment]
It actually turns out that it is created by `make run`, since that it is when it's needed. But it's entirely conceivable that someone running `make` should expect everything to be in a runnable state afterward (if they were to manually run `node app.js` or copy files somewhere), so I've added a `config` target to `all` that will generate the config files with a plain `make` command.
