### ISSUE TITLE
Remove ready confirmation

### ISSUE THREAD

**Issue by arxanas** [arxanas/drafts.ninja#20]
After having implemented ready confirmation, there really appears to be no good use case. People don't seem to like marking themselves as ready; and checking it by default would mostly invite trolling. This is a good candidate for a feature that should be cut so as to avoid feature debt, unless someone has a reason to keep it.

Remember to update the README to remove that feature from the list.

**Comment by tooomm** [comment]
In theory this feature sounds awesome!
I never used/tested it... but just by thinking it looks reasonable to have another road block to avoid unavailable players during a draft - it's the most annoying thing. Better wait beforehand (and remember, people still need to get used to the changed behavior!), instead of starting all over again after pick 3. It shouldn't be too annoying for users since it's just a little click. If valued against the trouble with people who haven't been ready yet for whatever reason. To me it sounds better to kick people who're not getting ready before starting :)

People could still immediately mark themselves as ready, even if they go afk for a few mins.
Would there be a way to check if people are active and uncheck the `ready` state if they are inactive for ~1min?

**Comment by arxanas** [comment]
Ideally we could detect if a user was not active, but it Is a hard problem. I already implement a connection monitor to this end. It is easy to get true positives, but hard to get true negatives. 

It is possible for a user to join a draft and leave it in a background tab, waiting for a beep to be notified when the draft starts. (Indeed, I myself am the sort of user to do this.) In this case, there is really no way to ascertain whether they are still connected, beyond the already-implemented connection monitor. 

The ready confirmation does not help in this regard. Since users can indeed mark themselves as ready but then go AFK, it does not serve to indicate true negatives (to verify that a user is in truth active), and it will rarely indicate true positives since a user will usually mark themself as active immediately upon joining the room. 

The host can already kick unresponsive users during the draft anyways, replacing them with bots. Since the feature has little predictive about power and doesn't let us do anything we can't already do manually, I am inclined to remove it to avoid increasing technical debt. 

cc @tritoch, if you have any thoughts.
