### ISSUE TITLE
implement proper draft timings

### ISSUE THREAD

**Issue by tooomm** [arxanas/drafts.ninja#48]
Right now the timing is fixed and always the same, you set it before the draft starts
As a result, you might be short on time on the first picks, and at the end you've plenty of time and the draft gets slowed down for no reason.

Could be optional or a tick box with `use decremental timings for fewer cards` for example

Official competitiv REL timings are:

| Cards remaining in pack | Time allotted |
|---------|---------|
 |15 cards | 40 seconds |
 |14 cards | 40 seconds |
 |13 cards | 35 seconds |
 |12 cards | 30 seconds |
 |11 cards | 25 seconds |
 |10 cards | 25 seconds | 
 |9 cards | 20 seconds |
 |8 cards | 20 seconds |
 |7 cards | 15 seconds |
 |6 cards | 10 seconds |
 |5 cards | 10 seconds |
 |4 cards | 5 seconds |
 |3 cards | 5 seconds |
 |2 cards | 5 seconds |
 |1 card | N/A |

check: http://www.wizards.com/contentresources/wizards/wpn/main/documents/magic_the_gathering_tournament_rules_pdf1.pdf

I would also like to see at least an option for a review time between packs!

**Comment by dev-id** [comment]
I'm testing 3 timer options currently live on http://beta.dr4ft.com

Magic Tournament Rules (MTR) - `Fast` - The timers from the table you specified. These are MUCH faster than existing timers. Only recommended for competitive drafts. Currently no review time, but since you have live review during the draft, maybe not necessary?

MTG Online (MTGO / MODO) - `Slow` - These timers are taken from MTGO. In array format, from 1st pick to last pick left-to-right, they look like this: `[75,70,65,60,55,50,45,40,35,30,25,20,15,10,5]` These timings have an overall (if every pick went to time) timing similar to the current system.

Average - `Moderate` - An approximate average of the above two. `[55,51,47,43,38,34,30,26,22,18,14,10,6,5]`

If a pack should have more than 15 cards, the middle time is repeated.

**Comment by tooomm** [comment]
What used the old default timings to be?
And how did they work again? Can you shortly explain for everybody please?

I just finished a real draft and got very positive feeedback on the speedy fast timing - no complains of anybody. Told them beforehand for sure, so that they know...

>If a pack should have more than 15 cards, the middle time is repeated.

Which means?

**Comment by dev-id** [comment]
> What used the old default timings to be?

Old timings were 40 (default, adjustable down to 1 or up to uhhh max int) + number of cards in pack * 1
Default would then be [54,53,52,51,50,49,48,47,46,45,44,43,autopick] for sets with basic lands

> Which means?

Middle time is median time.  So for MTR/Fast an additional 20s timer would be inserted into the middle (picks 8,9,10,etc) for every card over 15.

**Comment by tooomm** [comment]
See changelog on dr4ft.com site:
>2017-03-18: Changed timers to match official. Fast = Magic Tournament Rules. Slow = MTGO. Moderate = In between the two.

--> https://github.com/dr4fters/dr4ft/commit/998c323b1de10f169df9d670254317d3bccd107d#diff-1303e01c34edc3012abe181ba77fcb94
